### ISSUE TITLE
Polymorphic related resources requiring a named route and controller

### ISSUE THREAD

**Issue by adambedford** [JSONAPI-Resources/jsonapi-resources#1113]
If I'm reading this code correctly, when a relationship is polymorphic, a named route and controller are required:

`lib/jsonapi/routing_ext.rb#215`:
```
if relationship.polymorphic?
  options[:controller] ||= relationship.class_name.underscore.pluralize
else
  related_resource = JSONAPI::Resource.resource_for(resource_type_with_module_prefix(relationship.class_name.underscore.pluralize))
  options[:controller] ||= related_resource._type.to_s
end
```

With models like this:
```
class Message < ApplicationRecord
  belongs_to :subject, polymorphic: true
end
```

```
class Subject < ApplicationRecord
  has_many :messages, as: :subject
end
```

I end up with routes like: 
```
api_v1_message_subject GET       /api/v1/messages/:message_id/subject(.:format)     api/v1/subjects#get_related_resource {:format=>:json, :relationship=>"subject", :source=>"api/v1/messages"}
api_v1_messages        GET       /api/v1/messages(.:format)                         api/v1/messages#index {:format=>:json}
                       POST      /api/v1/messages(.:format)                         api/v1/messages#create {:format=>:json}
api_v1_message         GET       /api/v1/messages/:id(.:format)                     api/v1/messages#show {:format=>:json}
                       PATCH     /api/v1/messages/:id(.:format)                     api/v1/messages#update {:format=>:json}
                       PUT       /api/v1/messages/:id(.:format)                     api/v1/messages#update {:format=>:json}
                       DELETE    /api/v1/messages/:id(.:format)                     api/v1/messages#destroy {:format=>:json}
```

And an error:

```
ActionController::RoutingError (uninitialized constant Api::V1::SubjectsController)
```

Is this intentional? It doesn't seem right that a controller and resource are required in the name of a polymorphic relation.

**Comment by senid231** [comment]
reproduced with bug report
```ruby
begin
  require 'bundler/inline'
  require 'bundler'
rescue LoadError => e
  STDERR.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true, ui: ENV['SILENT'] ? Bundler::UI::Silent.new : Bundler::UI::Shell.new) do
  source 'https://rubygems.org'

  gem 'rails', require: false

  if ENV['JSONAPI_RESOURCES_PG']
    gem 'pg'
  else
    gem 'sqlite3', platform: :mri
    gem 'activerecord-jdbcsqlite3-adapter',
        git: 'https://github.com/jruby/activerecord-jdbc-adapter',
        branch: 'rails-5',
        platform: :jruby
  end

  if ENV['JSONAPI_RESOURCES_PATH']
    gem 'jsonapi-resources', path: ENV['JSONAPI_RESOURCES_PATH'], require: false
  else
    gem 'jsonapi-resources', git: 'https://github.com/cerebris/jsonapi-resources', require: false
  end

end

# prepare active_record database
require 'active_record'

class NullLogger < Logger
  def initialize(*_args)
  end

  def add(*_args, &_block)
  end
end

if ENV['JSONAPI_RESOURCES_PG']
  db_name = ENV['JSONAPI_RESOURCES_PG']
  system("psql -c 'DROP DATABASE IF EXISTS #{db_name};'")
  system("psql -c 'CREATE DATABASE #{db_name};'")
  ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: db_name)
else
  ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
end

ActiveRecord::Base.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
ActiveRecord::Migration.verbose = !ENV['SILENT']

ActiveRecord::Schema.define do
  # Add your schema here
  create_table :reviews, force: true do |t|
    t.string :content
    t.integer :rank
    t.integer :reviewable_id, null: false
    t.string :reviewable_type, null: false
  end

  create_table :authors, force: true do |t|
    t.string :name
  end

  create_table :posts, force: true do |t|
    t.string :content
    t.integer :author_id, null: false
  end
end

# create models
class Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic: true
end

class Author < ActiveRecord::Base
  has_many :reviews, as: :reviewable
  has_many :posts
end

class Post < ActiveRecord::Base
  has_many :reviews, as: :reviewable
  belongs_to :author
end

# prepare rails app
require 'action_controller/railtie'
# require 'action_view/railtie'
require 'jsonapi-resources'

class ApplicationController < ActionController::Base
end

# prepare jsonapi resources and controllers
class ReviewsController < ApplicationController
  include JSONAPI::ActsAsResourceController
end

class ReviewResource < JSONAPI::Resource
  attribute :content
  has_one :reviewable, polymorphic: true
end

class AuthorResource < JSONAPI::Resource
  attribute :name
end

class PostResource < JSONAPI::Resource
  attribute :content
end

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
  Rails.logger = config.logger

  secrets.secret_token = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.eager_load = false
end

# initialize app
Rails.application.initialize!

JSONAPI.configure do |config|
  config.json_key_format = :underscored_key
  config.route_format = :underscored_key
end

# draw routes
Rails.application.routes.draw do
  jsonapi_resources :reviews, only: [:show]
end

# prepare tests
require 'minitest/autorun'
require 'rack/test'

# Replace this with the code necessary to make your test fail.
class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_fetch_review_include_reviewable_author
    author = Author.create! name: 'John Doe'
    review = Review.create! reviewable: author, content: 'test'
    get "/reviews/#{review.id}", { include: 'reviewable' }, json_api_headers
    assert last_response.ok?
    relationship_data = { id: author.id.to_s, type: 'authors' }
    assert_equal relationship_data, last_response_json[:data][:relationships][:reviewable][:data]
    assert_equal relationship_data, last_response_json[:included].first.slice(:id, :type)
  end

  def test_fetch_review_include_reviewable_post
    author = Author.create! name: 'John Doe'
    post = Post.create! content: 'test', author: author
    review = Review.create! reviewable: post, content: 'test2'
    get "/reviews/#{review.id}", { include: 'reviewable' }, json_api_headers
    assert last_response.ok?
    relationship_data = { id: post.id.to_s, type: 'posts' }
    assert_equal relationship_data, last_response_json[:data][:relationships][:reviewable][:data]
    assert_equal relationship_data, last_response_json[:included].first.slice(:id, :type)
  end

  private

  def json_api_headers
    {'Accept' => JSONAPI::MEDIA_TYPE, 'CONTENT_TYPE' => JSONAPI::MEDIA_TYPE}
  end

  def last_response_json
    JSON.parse(last_response.body).deep_symbolize_keys
  end

  def app
    Rails.application
  end
end
```
failure log
```
I, [2017-09-13T10:18:25.187926 #12320]  INFO -- : Started GET "/reviews/1?include=reviewable" for 127.0.0.1 at 2017-09-13 10:18:25 +0300
I, [2017-09-13T10:18:25.190310 #12320]  INFO -- : Processing by ReviewsController#show as HTML
I, [2017-09-13T10:18:25.190359 #12320]  INFO -- :   Parameters: {"include"=>"reviewable", "id"=>"1"}
E, [2017-09-13T10:18:25.191549 #12320] ERROR -- : Internal Server Error: JSONAPI: Could not find resource 'reviewable'. (Class ReviewableResource not found) /home/senid/projects/forked/jsonapi-resources/lib/jsonapi/resource.rb:511:in `resource_klass_for'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/relationship.rb:29:in `resource_klass'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/core_ext/object/try.rb:17:in `public_send'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/core_ext/object/try.rb:17:in `try!'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/core_ext/object/try.rb:6:in `try'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:55:in `block in get_related'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:50:in `each'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:50:in `get_related'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:84:in `block in parse_include'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:82:in `each'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:82:in `parse_include'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:27:in `block in initialize'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:26:in `each'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/include_directives.rb:26:in `initialize'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/request_parser.rb:364:in `new'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/request_parser.rb:364:in `parse_include_directives'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/request_parser.rb:132:in `setup_show_action'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/request_parser.rb:55:in `setup_base_op'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/request_parser.rb:28:in `each'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/acts_as_resource_controller.rb:81:in `block (2 levels) in process_request'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/acts_as_resource_controller.rb:80:in `block in process_request'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/acts_as_resource_controller.rb:115:in `process_operations'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/acts_as_resource_controller.rb:79:in `process_request'
/home/senid/projects/forked/jsonapi-resources/lib/jsonapi/acts_as_resource_controller.rb:23:in `show'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in `process'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal.rb:189:in `dispatch'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_controller/metal.rb:253:in `dispatch'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `each'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `serve'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/railties-5.1.4/lib/rails/rack/logger.rb:26:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-test-0.7.0/lib/rack/mock_session.rb:30:in `request'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-test-0.7.0/lib/rack/test.rb:249:in `process_request'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/rack-test-0.7.0/lib/rack/test.rb:59:in `get'
/home/senid/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/forwardable.rb:183:in `get'
/home/senid/projects/forked/jsonapi-resources/lib/bug_report_templates/custom_bug_report_local.rb:155:in `test_fetch_review_include_reviewable'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:107:in `block (3 levels) in run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:204:in `capture_exceptions'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:104:in `block (2 levels) in run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:255:in `time_it'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:103:in `block in run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:350:in `on_signal'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:275:in `with_info_handler'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest/test.rb:102:in `run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:839:in `run_one_method'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:324:in `run_one_method'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:311:in `block (2 levels) in run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:310:in `each'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:310:in `block in run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:350:in `on_signal'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:337:in `with_info_handler'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:309:in `run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:159:in `block in __run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:159:in `map'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:159:in `__run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:136:in `run'
/home/senid/.rvm/gems/ruby-2.2.4@jsonapi-resources_bug-report-template/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
I, [2017-09-13T10:18:25.199240 #12320]  INFO -- : Completed 500 Internal Server Error in 9ms (Views: 1.2ms)
```

**Comment by senid231** [comment]
but if we changes code like this
```ruby
class ReviewResource < JSONAPI::Resource
  attribute :content
  has_one :reviewable, polymorphic: true, class_name: 'Author'
end
```
tests are passed
```
I, [2017-09-13T10:24:35.414377 #12673]  INFO -- : Started GET "/reviews/2?include=reviewable" for 127.0.0.1 at 2017-09-13 10:24:35 +0300
I, [2017-09-13T10:24:35.415009 #12673]  INFO -- : Processing by ReviewsController#show as HTML
I, [2017-09-13T10:24:35.415057 #12673]  INFO -- :   Parameters: {"include"=>"reviewable", "id"=>"2"}
D, [2017-09-13T10:24:35.417930 #12673] DEBUG -- :    (0.5ms)  SELECT reviews.id FROM "reviews" WHERE "reviews"."id" = ?  [["id", 2]]
D, [2017-09-13T10:24:35.419555 #12673] DEBUG -- :    (0.2ms)  SELECT reviews.id, reviews.reviewable_id, reviews.reviewable_type FROM "reviews" WHERE "reviews"."id" = 2
D, [2017-09-13T10:24:35.421958 #12673] DEBUG -- :   Review Load (0.2ms)  SELECT "reviews".* FROM "reviews" WHERE "reviews"."id" = 2
D, [2017-09-13T10:24:35.423998 #12673] DEBUG -- :   Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = 2
I, [2017-09-13T10:24:35.425012 #12673]  INFO -- :   Rendering text template
I, [2017-09-13T10:24:35.425111 #12673]  INFO -- :   Rendered text template (0.0ms)
I, [2017-09-13T10:24:35.425255 #12673]  INFO -- : Completed 200 OK in 10ms (Views: 0.4ms)

I, [2017-09-13T10:24:35.316979 #12673]  INFO -- : Started GET "/reviews/1?include=reviewable" for 127.0.0.1 at 2017-09-13 10:24:35 +0300
I, [2017-09-13T10:24:35.324551 #12673]  INFO -- : Processing by ReviewsController#show as HTML
I, [2017-09-13T10:24:35.324608 #12673]  INFO -- :   Parameters: {"include"=>"reviewable", "id"=>"1"}
D, [2017-09-13T10:24:35.326949 #12673] DEBUG -- :    (0.1ms)  SELECT reviews.id FROM "reviews" WHERE "reviews"."id" = ?  [["id", 1]]
D, [2017-09-13T10:24:35.397937 #12673] DEBUG -- :    (12.0ms)  SELECT reviews.id, reviews.reviewable_id, reviews.reviewable_type FROM "reviews" WHERE "reviews"."id" = 1
D, [2017-09-13T10:24:35.402121 #12673] DEBUG -- :   Review Load (2.0ms)  SELECT "reviews".* FROM "reviews" WHERE "reviews"."id" = 1
D, [2017-09-13T10:24:35.407000 #12673] DEBUG -- :   Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = 1
I, [2017-09-13T10:24:35.410445 #12673]  INFO -- :   Rendering text template
I, [2017-09-13T10:24:35.410540 #12673]  INFO -- :   Rendered text template (0.0ms)
I, [2017-09-13T10:24:35.410688 #12673]  INFO -- : Completed 200 OK in 86ms (Views: 3.0ms)
```

**Comment by senid231** [comment]
@adambedford this is definitely a bug, but you can use hack from upper comment, or just create resource class like
```ruby
class ReviewableResource < JSONAPI::Resource
end
```

**Comment by adambedford** [comment]
@senid231 Thanks for this fantastic and thorough reproduction! 

I think creating a `ReviewableResource` isn't the complete solution because the next error will be "Can't find `ReviewablesController`"

I suppose I could specify the `class_name` on the polymorphic relationship since I actually only have one polymorphic type at the moment, but this won't work long-term with a `Review` can belong to multiple types of `reviewable`.

Definitely seems like a bug, and it's odd because there's an explicit code path for polymorphic relationships that causes the problem, which makes me think it was done on purpose for some reason..........

**Comment by senid231** [comment]
@adambedford "Can't find `ReviewablesController`" will only be raised if you add `jsonapi_resources :reviewables` to `config/routes.rb` but you don't need that - relationship routes are handled by parent (`josnpi_resources :reviews` in our case)
So these solutions are actually same

**Comment by adambedford** [comment]
@senid231 The routing looks like this:

```
jsonapi_resources :messages do
  jsonapi_relationships
end
```

Which produces the following relationship route:
```
api_v1_message_subject GET       /api/v1/messages/:message_id/subject(.:format)     api/v1/subjects#get_related_resource {:format=>:json, :relationship=>"subject", :source=>"api/v1/messages"}
```

For some reason it's trying to get to the `api/v1/subjects` controller

**Comment by adambedford** [comment]
For anyone that comes looking, the way around this is to specify `controller: "messages"` to force the use of `MessagesController#get_related_resources`
