### ISSUE TITLE
Enabling caching on resource causes Internal Server Error: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by kbroderick** [JSONAPI-Resources/jsonapi-resources#1126]
I've added a read-only JSON API to our existing Rails app and am now looking at improving performance. When I attempt to enable caching (added `config.resource_cache = Rails.cache` to `jsonapi_resources.rb` initialization script and `caching` keyword to one of my _resource definitions), I get a crash with this stack trace:

    Internal Server Error: undefined method `id' for nil:NilClass /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/resource_serializer.rb:60:in `block     in serialize_to_hash'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/resource_serializer.rb:59:in `each'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/resource_serializer.rb:59:in `serialize_to_hash'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/response_document.rb:111:in `results_to_hash'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/response_document.rb:12:in `contents'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:226:in `render_results'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:78:in `process_request'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:60:in `get_related_resources'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/abstract_controller/base.rb:188:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:90:in `run_callbacks'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal/rescue.rb:20:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/notifications.rb:164:in `block in instrument'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/notifications.rb:164:in `instrument'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activerecord-5.0.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/abstract_controller/base.rb:126:in `process'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionview-5.0.6/lib/action_view/rendering.rb:30:in `process'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-mini-profiler-0.10.5/lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_controller/metal.rb:262:in `dispatch'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:32:in `serve'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:39:in `block in serve'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:26:in `each'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:26:in `serve'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:727:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/bullet-5.6.1/lib/bullet/rack.rb:12:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activerecord-5.0.6/lib/active_record/migration.rb:553:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:90:in `run_callbacks'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/rack/logger.rb:36:in `call_app'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `block in call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:26:in `tagged'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `tagged'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/request_id.rb:24:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/actionpack-5.0.6/lib/action_dispatch/middleware/static.rb:136:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-mini-profiler-0.10.5/lib/mini_profiler/profiler.rb:282:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/engine.rb:522:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `public_send'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `method_missing'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/handler/thin.rb:22:in `run'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/commands/server.rb:104:in `start'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:90:in `block in server'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:85:in `tap'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:85:in `server'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
    /Users/user/Documents/src/project/bin/rails:9:in `require'
    /Users/user/Documents/src/project/bin/rails:9:in `<top (required)>'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
    /Users/user/.rvm/gems/ruby-2.4.1@50/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
    /Users/user/Documents/src/project/bin/spring:15:in `require'
    /Users/user/Documents/src/project/bin/spring:15:in `<top (required)>'
    bin/rails:3:in `load'
    bin/rails:3:in `<main>'

I am overriding records in the resource definition, but I am not using records_for, which is the only thing I've been able to find suggested as a possible cause.

I'm assuming this is more likely to be an issue with my use of the gem than the gem itself, but if someone could point me in the correct direction for resolving it, I'd appreciate it.

**Comment by kbroderick** [comment]
OK, on further investigation, the resource collection somehow had a nil element, I believe due to a scope mismatch (the scope on the resource from which I was requesting child resources wasn't as narrow as the scope on the child resource records itself).
