### ISSUE TITLE
enable caching - Internal Server Error: File name too long @ rb_sysopen

### ISSUE THREAD

**Issue by butchmarshall** [JSONAPI-Resources/jsonapi-resources#1139]
This works fine if I don't add caching to my resource. 

It looks like my system does not like full file paths longer than 194 characters?  Running ubuntu 16.04

Errno::ENOENT: No such file or directory
```
2.2.1 :037 > File.open("/home/butch/workspace/snow_trails_server/tmp/cache/trails%2Ff7a46333-e381-5776-a9df-79a32fa17e58%2F533995193398906758%2FSRLZ-TR8PYiZg5045bJ992iLizOvKGPOl%2B3y0QNTrO9I5J5w%3D%2FATTR-CTX-dCNOmK_nS")
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/butch/workspace/snow_trails_server/tmp/cache/trails%2Ff7a46333-e381-5776-a9df-79a32fa17e58%2F533995193398906758%2FSRLZ-TR8PYiZg5045bJ992iLizOvKGPOl%2B3y0QNTrO9I5J5w%3D%2FATTR-CTX-dCNOmK_nS
        from (irb):37:in `initialize'
        from (irb):37:in `open'
        from (irb):37
        from /home/butch/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

Errno::ENAMETOOLONG: File name too long @ rb_sysopen
```
2.2.1 :038 > File.open("/home/butch/workspace/snow_trails_server/tmp/cache/trails%2Ff7a46333-e381-5776-a9df-79a32fa17e58%2F533995193398906758%2FSRLZ-TR8PYiZg5045bJ992iLizOvKGPOl%2B3y0QNTrO9I5J5w%3D%2FATTR-CTX-dCNOmK_nSY")
Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /home/butch/workspace/snow_trails_server/tmp/cache/trails%2Ff7a46333-e381-5776-a9df-79a32fa17e58%2F533995193398906758%2FSRLZ-TR8PYiZg5045bJ992iLizOvKGPOl%2B3y0QNTrO9I5J5w%3D%2FATTR-CTX-dCNOmK_nSY
        from (irb):38:in `initialize'
        from (irb):38:in `open'
        from (irb):38
```

My Resource:

```
class TrailResource < JSONAPI::Resource
	caching
	key_type :uuid
	attributes :coordinates, :trail_location, :trail_status, :trail_type, :trail_region, :updated_at
	filter :updated_at
end
```

The error:

```
Internal Server Error: File name too long @ rb_sysopen - /home/butch/workspace/snow_trails_server/tmp/cache/trails%2Ff7a46333-e381-5776-a9df-79a32fa17e58%2F533995193398906758%2FSRLZ-TR8PYiZg5045bJ992iLizOvKGPOl%2B3y0QNTrO9I5J5w%3D%2FATTR-CTX-dCNOmK_nSY%2B12vHzasLXiswzlGT5UHA7jAGYkvmCuQs%3D20171209-25566-1tntexp /home/butch/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tempfile.rb:133:in `initialize'
/home/butch/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tempfile.rb:133:in `open'
/home/butch/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tempfile.rb:133:in `block in initialize'
/home/butch/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tmpdir.rb:130:in `create'
/home/butch/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tempfile.rb:131:in `initialize'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/core_ext/file/atomic.rb:21:in `new'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/core_ext/file/atomic.rb:21:in `atomic_write'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:83:in `write_entry'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/cache.rb:391:in `block in write'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/cache.rb:547:in `block in instrument'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/cache.rb:547:in `instrument'
/home/butch/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/cache.rb:389:in `write'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/cached_response_fragment.rb:105:in `write'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:594:in `block (2 levels) in populate_resource_set'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:590:in `each'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:590:in `block in populate_resource_set'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:546:in `each_key'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:546:in `populate_resource_set'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:368:in `find_resource_set'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:97:in `show'
/home/butch/.rvm/gems/ruby-2.4.2/bundler/gems/jsonapi-resources-3a02a4d2e149/lib/jsonapi/processor.rb:34:in `block (2 levels) in process'

```

**Comment by butchmarshall** [comment]
This is some odd issue with my system.   It's working fine on other ubuntu systems with longer path lengths...

**Comment by butchmarshall** [comment]
Looks like I'm hitting this: https://ubuntuforums.org/showthread.php?t=1173541

The solution is to change the Rails cache directory away from the encrypted home directory.

e.g.

`config.cache_store = :file_store, "/tmp"`

**Comment by rvalyi** [comment]
just to mention your report just saved me hours of googling while testing Akretion Shopinvader, I will see with @sebastienbeau what is the best way to fix this in our default docker-compose file. In our case we have to use some directory like /tmp/shopinvader from the host to mount as the app tmp directory to avoid this issue. Will reference this soon. So thank you for the report anyway.
