### ISSUE TITLE
serialize_to_hash: undefined method `_type'

### ISSUE THREAD

**Issue by john-griffin** [JSONAPI-Resources/jsonapi-resources#117]
I've been trying to integrate with a fairly basic project but whenever I serialize an object I get the error

```
NoMethodError: undefined method `_type' for #<Class:0x007faa896d8b08>
    from /Users/john/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
    from /Users/john/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/jsonapi-resources-ba8d7b40d61f/lib/jsonapi/resource_serializer.rb:129:in `attribute_hash'
```

Serializing by doing: 

``` ruby
serializer = JSONAPI::ResourceSerializer.new(CrawlResource)
serializer.serialize_to_hash(Crawl.first)
```

Tried on `0.2.0` and `master`. Does anything leap out?

**Comment by lgebhardt** [comment]
You need to make sure you pass a Resource to the serializer. This should work:

``` ruby
serializer = JSONAPI::ResourceSerializer.new(CrawlResource)
serializer.serialize_to_hash(CrawlResource.new(Crawl.first))
```

**Comment by john-griffin** [comment]
@lgebhardt thanks for clarifying, that works
