### ISSUE TITLE
Rails 5: Tests don't run in default configuration

### ISSUE THREAD

**Issue by carlthuringer** [JSONAPI-Resources/jsonapi-resources#1180]
### Bug report

`ruby 2.4.4`
`jsonapi-resources 0.9.3`

Tests do not execute in default configuration.

```
/Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/reflection.rb:436:in `initialize': A class was passed to `:class_name` but we are expecting a string. (ArgumentError)
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/reflection.rb:31:in `new'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/reflection.rb:31:in `create'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/builder/association.rb:45:in `create_reflection'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/builder/association.rb:31:in `build'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations.rb:1654:in `belongs_to'
	from /Users/carlthuringer/Workspace/hatch/jsonapi-resources/test/fixtures/active_record.rb:625:in `<class:RelatedThing>'
	from /Users/carlthuringer/Workspace/hatch/jsonapi-resources/test/fixtures/active_record.rb:624:in `<top (required)>'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /Users/carlthuringer/Workspace/hatch/jsonapi-resources/test/test_helper.rb:208:in `<top (required)>'
	from /Users/carlthuringer/Workspace/hatch/jsonapi-resources/test/controllers/controller_test.rb:1:in `require'
	from /Users/carlthuringer/Workspace/hatch/jsonapi-resources/test/controllers/controller_test.rb:1:in `<top (required)>'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `require'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `select'
	from /Users/carlthuringer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
```

**Comment by lgebhardt** [comment]
Closing with #1181
