### ISSUE TITLE
regression of filters on association

### ISSUE THREAD

**Issue by senid231** [JSONAPI-Resources/jsonapi-resources#1214]
## This issue is a (choose one):

- [x] Problem/bug report.
- [ ] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [ ] I've searched for an existing issue.
- [ ] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [x] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [x] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

## Description

Choose one section below and delete the other:

### Bug reports:
```bash
$ RAILS_VERSION="~> 5.2" JSONAPI_RESOURCES_VERSION="~> 0.9" bug_report_with_filter.rb
```
`bug_report_with_filter.rb`
```ruby
begin
  require 'bundler/inline'
  require 'bundler'
rescue LoadError => e
  STDERR.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true, ui: ENV['SILENT'] ? Bundler::UI::Silent.new : Bundler::UI::Shell.new) do
  source 'https://rubygems.org'

  git_source(:github) do |repo_name|
    repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
    "https://github.com/#{repo_name}.git"
  end

  if ENV['RAILS_VERSION']
    gem 'rails', ENV['RAILS_VERSION'], require: false
  else
    gem 'rails', require: false
  end


  if ENV['JSONAPI_RESOURCES_PG']
    gem 'pg'
  else
    gem 'sqlite3'
  end

  if ENV['JSONAPI_RESOURCES_PATH']
    gem 'jsonapi-resources', path: ENV['JSONAPI_RESOURCES_PATH'], require: false
  elsif ENV['JSONAPI_RESOURCES_VERSION']
    gem 'jsonapi-resources', ENV['JSONAPI_RESOURCES_VERSION'], require: false
  else
    gem 'jsonapi-resources', github: 'cerebris/jsonapi-resources', require: false
  end

end

require 'active_record'

class NullLogger < Logger
  def initialize(*_args)
  end

  def add(*_args, &_block)
  end
end

if ENV['JSONAPI_RESOURCES_PG']
  db_name = ENV['JSONAPI_RESOURCES_PG']
  system("psql -c 'DROP DATABASE IF EXISTS #{db_name};'")
  system("psql -c 'CREATE DATABASE #{db_name};'")
  ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: db_name)
else
  ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
end

ActiveRecord::Base.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
ActiveRecord::Migration.verbose = !ENV['SILENT']

## /db/schema.rb
ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
    t.string :name
  end

  create_table :posts, force: true do |t|
    t.integer :author_id
    t.string :title
    t.string :content
  end
end

## /app/models/
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Author < ApplicationRecord
  has_many :posts
end

class Post < ApplicationRecord
  belongs_to :author
end

require 'action_controller/railtie'
# require 'action_view/railtie'
require 'jsonapi-resources'

## /app/controllers/
class ApplicationController < ActionController::Base
  include JSONAPI::ActsAsResourceController
end

class JsonApiController < ApplicationController
  include JSONAPI::ActsAsResourceController
end

class AuthorsController < JsonApiController
end

class PostsController < JsonApiController
end

## /app/resources/
class BaseResource < JSONAPI::Resource
  abstract
end

class AuthorResource < BaseResource
  attributes :name
  has_many :posts
end

class PostResource < BaseResource
  attributes :title, :content
  has_one :author

  filter :title
  filter :'author.name'
  filter :'author.id', apply: -> (records, values, _opts) do
    records.where(author_id: values)
  end
end

## /config/application.rb
class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.logger = ENV['SILENT'] ? NullLogger.new : Logger.new(STDOUT)
  Rails.logger = config.logger

  secrets.secret_token = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.eager_load = false
end

Rails.application.initialize!

JSONAPI.configure do |config|
  config.json_key_format = :underscored_key
  config.route_format = :underscored_key
end

## /config/routes.rb
Rails.application.routes.draw do
  jsonapi_resources :posts
end

## /test/
require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_correct_filter
    author = Author.create!(name: 'John')
    post = Post.create!(title: 'qwe', author: author)
    get "/posts", {filter: { 'author.id': author.id } }, json_api_headers
    assert last_response.ok?
    assert_equal 1, last_response_json[:data].size
    assert_equal post.title, last_response_json[:data][0][:attributes][:title]
  end

  private

  def last_response_json
    JSON.parse(last_response.body).deep_symbolize_keys
  end

  def json_api_headers
    {Accept: JSONAPI::MEDIA_TYPE, CONTENT_TYPE: JSONAPI::MEDIA_TYPE}.stringify_keys
  end

  def app
    Rails.application
  end
end
```
output
```
Testing started at 11:41 AM ...
bash -c "/home/senid/.rvm/bin/rvm ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template do /home/senid/.rvm/rubies/ruby-2.3.8-railsexpress/bin/ruby -Itest /home/senid/projects/forked/jsonapi-resources/custom_bug_reports/custom_bug_report_filter_with_dot.rb"
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.2
Using concurrent-ruby 1.1.4
Using i18n 1.5.2
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.2
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.1
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.2
Using rack 2.0.6
Using rack-test 1.1.0
Using actionpack 5.2.2
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 5.2.2
Using globalid 0.4.2
Using activejob 5.2.2
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 5.2.2
Using activemodel 5.2.2
Using arel 9.0.0
Using activerecord 5.2.2
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 5.2.2
Using bundler 1.16.6
Using method_source 0.9.2
Using thor 0.20.3
Using railties 5.2.2
Using jsonapi-resources 0.9.5
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.2
Using sqlite3 1.3.13
-- create_table(:authors, {:force=>true})
D, [2019-01-16T11:42:04.257046 #22596] DEBUG -- :    (0.1ms)  DROP TABLE IF EXISTS "authors"
D, [2019-01-16T11:42:04.258406 #22596] DEBUG -- :    (0.7ms)  SELECT sqlite_version(*)
D, [2019-01-16T11:42:04.258770 #22596] DEBUG -- :    (0.2ms)  CREATE TABLE "authors" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar)
   -> 0.0042s
-- create_table(:posts, {:force=>true})
D, [2019-01-16T11:42:04.259133 #22596] DEBUG -- :    (0.1ms)  DROP TABLE IF EXISTS "posts"
D, [2019-01-16T11:42:04.259455 #22596] DEBUG -- :    (0.1ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "author_id" integer, "title" varchar, "content" varchar)
   -> 0.0006s
D, [2019-01-16T11:42:04.277141 #22596] DEBUG -- :    (0.2ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
D, [2019-01-16T11:42:04.285680 #22596] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.2ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2019-01-16T11:42:04.294057 #22596] DEBUG -- :    (0.2ms)  begin transaction
D, [2019-01-16T11:42:04.296122 #22596] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.2ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "default_env"], ["created_at", "2019-01-16 09:42:04.294981"], ["updated_at", "2019-01-16 09:42:04.294981"]]
D, [2019-01-16T11:42:04.296652 #22596] DEBUG -- :    (0.1ms)  commit transaction
Started

D, [2019-01-16T11:42:04.746778 #22596] DEBUG -- :    (0.0ms)  begin transaction
D, [2019-01-16T11:42:04.747621 #22596] DEBUG -- :   Author Create (0.1ms)  INSERT INTO "authors" ("name") VALUES (?)  [["name", "John"]]
D, [2019-01-16T11:42:04.747939 #22596] DEBUG -- :    (0.1ms)  commit transaction
D, [2019-01-16T11:42:04.755018 #22596] DEBUG -- :    (0.1ms)  begin transaction
D, [2019-01-16T11:42:04.756138 #22596] DEBUG -- :   Post Create (0.2ms)  INSERT INTO "posts" ("author_id", "title") VALUES (?, ?)  [["author_id", 1], ["title", "qwe"]]
D, [2019-01-16T11:42:04.756403 #22596] DEBUG -- :    (0.0ms)  commit transaction
I, [2019-01-16T11:42:04.763598 #22596]  INFO -- : Started GET "/posts?filter[author.id]=1" for 127.0.0.1 at 2019-01-16 11:42:04 +0200
I, [2019-01-16T11:42:04.767079 #22596]  INFO -- : Processing by PostsController#index as HTML
I, [2019-01-16T11:42:04.767161 #22596]  INFO -- :   Parameters: {"filter"=>{"author.id"=>"1"}}
E, [2019-01-16T11:42:04.770350 #22596] ERROR -- : Internal Server Error: undefined method `include_config' for nil:NilClass /home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/request_parser.rb:268:in `block in parse_filters'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:338:in `block in each_pair'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:337:in `each_pair'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:337:in `each_pair'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/request_parser.rb:253:in `parse_filters'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/request_parser.rb:48:in `setup_index_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/request_parser.rb:38:in `setup_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/request_parser.rb:27:in `initialize'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/acts_as_resource_controller.rb:66:in `new'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/acts_as_resource_controller.rb:66:in `process_request'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/jsonapi-resources-0.9.5/lib/jsonapi/acts_as_resource_controller.rb:16:in `index'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in `process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in `process'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionview-5.2.2/lib/action_view/rendering.rb:32:in `process'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in `dispatch'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in `dispatch'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `each'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/conditional_get.rb:25:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/railties-5.2.2/lib/rails/rack/logger.rb:28:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
/home/senid/.rvm/rubies/ruby-2.3.8-railsexpress/lib/ruby/2.3.0/forwardable.rb:202:in `get'
/home/senid/projects/forked/jsonapi-resources/custom_bug_reports/custom_bug_report_filter_with_dot.rb:170:in `test_correct_filter'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
/home/senid/.rvm/gems/ruby-2.3.8-railsexpress@jsonapi-resources_bug-report-template/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
I, [2019-01-16T11:42:04.774450 #22596]  INFO -- : Completed 500 Internal Server Error in 7ms (Views: 1.2ms)


Finished in 0.03291s
1 tests, 1 assertions, 1 failures, 0 errors, 0 skips

Process finished with exit code 0

Minitest::Assertion: Expected false to be truthy.
```

**Comment by mupkoo** [comment]
Using the same filter like a relationship is not working as well. For example, calling the following resource with `filter[country]=1` is not using the custom filter.

```ruby
class ProjectResource < JSONAPI::Resource
  attribute :name

  relationship :country, to: :one, foreign_key_on: :related
  relationship :community, to: :one

  filter :country, apply: -> (records, value, _options) {
    # The callback does not get called
    records.joins(:community).where(communities: { country_id: value })
  }
end
```

**Comment by mupkoo** [comment]
I think that my problem is more related to #1147, so I added a comment there

**Comment by lgebhardt** [comment]
#1215 fixed this
