### ISSUE TITLE
Error: undefined method relationship for "":String .../lib/jsonapi/path_segment.rb:33:in eql?

### ISSUE THREAD

**Issue by reachire-smendola** [JSONAPI-Resources/jsonapi-resources#1377]
## This issue is a (choose one):

- [X] Problem/bug report.
- [ ] Feature request.
- [ ] Request for support. **Note: Please try to avoid submitting issues for support requests. Use [Gitter](https://gitter.im/cerebris/jsonapi-resources) instead.** 

## Checklist before submitting:

- [x] I've searched for an existing issue.
- [x] I've asked my question on [Gitter](https://gitter.im/cerebris/jsonapi-resources) and have not received a satisfactory answer.
- [ ] I've included a complete [bug report template](https://github.com/cerebris/jsonapi-resources/blob/master/lib/bug_report_templates/rails_5_master.rb). This step helps us and allows us to see the bug without trying to reproduce the problem from your description. It helps you because you will frequently detect if it's a problem specific to your project.
- [ ] The feature I'm asking for is compliant with the [JSON:API](http://jsonapi.org/) spec.

### Bug reports:

Occasionally, the server starts giving errors like this:
```
rails_1      | E, [2020-05-12T14:34:02.613861 #1] ERROR -- : [cbd6c33b-0846-4e3c-8477-1831b935119b] Internal Server Error: undefined method `relationship' for "":String /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/path_segment.rb:33:in `eql?'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:123:in `has_key?'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:123:in `add_join_details'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:179:in `block (2 levels) in perform_joins'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:144:in `each'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:144:in `block in perform_joins'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:143:in `each'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:143:in `perform_joins'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation/join_manager.rb:41:in `join'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation_resource.rb:720:in `apply_joins'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation_resource.rb:695:in `apply_request_settings_to_records'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation_resource.rb:400:in `find_related_monomorphic_fragments'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/active_relation_resource.rb:223:in `find_included_fragments'
rails_1      | /usr/local/bundle/bundler/gems/jsonapi-resources-25911bc19871/lib/jsonapi/processor.rb:441:in `block in load_included'
```

https://sentry.io/share/issue/b7f7c312a14e43aabd7e8c982613a4c6/

When it starts happening, it seems to continue to happen, but **restarting the server clears it up** (until it happens again radomly some time later). This has the feel of a caching bug? or perhaps something related to loading?

This started happening after upgrading Ruby from 2.6 to 2.7.  Another user reported seeing the same issue on Gitter, and for them it cleared up after downgrading Ruby. I would like to avoid doing that as there are features in 2.7 I'm already using.

**Comment by reachire-smendola** [comment]
I see now this is a dupe of  #1333 , now fixed.
