### ISSUE TITLE
Single Table Inheritance and records_for problem

### ISSUE THREAD

**Issue by jakubrohleder** [JSONAPI-Resources/jsonapi-resources#161]
Hi! I'm just migrating from jbuilder to this gem and I've encountered a problem, which I cannot solve.

I want to add two associations to the same resource, which use different scope depending on STI. More precisely:

My db structure is as follows:

there are Events with multiple Activities
each User can attend Event by EventInvitation
User can only see Activities to which EventInvitation is linked by ActivityRole
ActivityRole has two STI types: ActivityRoleHost and ActivityRoleAttendee (there are scopes attendee and host, column is type)

My model and resource: 

```
class Activity < ActiveRecord::Base
  # (...)
  has_many :activity_roles, :dependent => :destroy
  has_many :event_invitations, through: :activity_roles
  has_many :users, through: :event_invitations, source_type: 'User' do
    def hosts() merge(ActivityRole.hosts) end
    def attendees() merge(ActivityRole.attendees) end
  end
  # (...)
end

class V1::ActivityResource < AuthorizedResource
  # (...)
  has_many :attendees, class_name: 'User', foreign_key: 'user_ids'
  has_many :hosts, class_name: 'User', foreign_key: 'user_ids'

  def records_for_hosts(options = {})
    @model.users.hosts
  end

  def records_for_attendeess(options = {})
    @model.users.attendees
  end
  # (...)
end
```

When i perform `get http://localhost:3000/v1/activities/1?include=attendees` I'm getting error:

```
NoMethodError (undefined method `_type' for #<Class:0x007f87aee63c90>):
  .bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:144:in `attribute_hash'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:128:in `object_hash'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:214:in `block (2 levels) in links_hash'
  .bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:46:in `each'
  .bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:46:in `each'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:210:in `block in links_hash'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:180:in `each'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:180:in `each_with_object'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:180:in `links_hash'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:129:in `object_hash'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:122:in `process_primary'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_serializer.rb:34:in `serialize_to_hash'
  .bundle/ruby/2.1.0/gems/jsonapi-resources-0.3.1/lib/jsonapi/resource_controller.rb:47:in `show'
  .bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  .bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/base.rb:189:in `process_action'
  .bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
  .bundle/ruby/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  .bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:113:in `call'
```

I tried multiple combinations of resource parameters but nothing seems to solve the problem. Am I doing something wrong?

**Comment by lgebhardt** [comment]
Just looking quickly, things look correct. 

Do you have a V1::UserResource defined in the project?

If you put a breakpoint on resource_serializer.rb:144, what type of object is `source`?

**Comment by jakubrohleder** [comment]
I'm so ashame, the reason was a typo: `records_for_attendeess` instead of `records_for_attendees`, it took me few hours to spot it.

Nevertheless thank you for such a quick answer and building this awesome gem!

**Comment by lgebhardt** [comment]
@JakubRohleder, sorry I should have mentioned that. I saw it at first and assumed you didn't want to deal with the infection code. Glad you found it.
