### ISSUE TITLE
uninitialized constant JSONAPI error with config.eager_load = true

### ISSUE THREAD

**Issue by seizadi** [JSONAPI-Resources/jsonapi-resources#248]
Following the site README with new test project. I have error w/ controller generation with config.eager_load = true, when I turn it off the error goes away.
-Soheil

$ rails g controller Users --skip-assets
/Users/seizadi/hadoop/rails-projects/threatfeed/jsonapi/tfwebserver/app/controllers/application_controller.rb:1:in `<top (required)>': uninitialized constant JSONAPI (NameError)
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:472:in`block (2 levels) in eager_load!'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `each'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in`block in eager_load!'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `each'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in`eager_load!'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:346:in `eager_load!'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in`each'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in`instance_exec'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in`block (2 levels) in each_strongly_connected_component'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in`block in each_strongly_connected_component'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in`call'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in`tsort_each'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in`run_initializers'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
    from /Users/seizadi/hadoop/rails-projects/threatfeed/jsonapi/tfwebserver/config/environment.rb:5:in`<top (required)>'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:92:in `require'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:92:in`preload'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:131:in`block in run'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in`run'
    from /Users/seizadi/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /Users/seizadi/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in`<main>'

**Comment by seizadi** [comment]
Sorry, this was my error did not include Gem in Gemfile.
