### ISSUE TITLE
exception in JSONAPI::Request#parse_sort_criteria

### ISSUE THREAD

**Issue by senid231** [JSONAPI-Resources/jsonapi-resources#270]
if you send request like:

```
http://127.0.0.1:300/json_api/contacts?sort=
```

application raise exception

```
<NoMethodError> undefined method `collect' for nil:NilClass

/var/www/api/shared/bundle/ruby/2.1.0/bundler/gems/jsonapi-resources-30969a3b929d/lib/jsonapi/request.rb:238:in `parse_sort_criteria'
/var/www/api/shared/bundle/ruby/2.1.0/bundler/gems/jsonapi-resources-30969a3b929d/lib/jsonapi/request.rb:47:in `setup_index_action'
/var/www/api/shared/bundle/ruby/2.1.0/bundler/gems/jsonapi-resources-30969a3b929d/lib/jsonapi/request.rb:35:in `setup_action'
/var/www/api/shared/bundle/ruby/2.1.0/bundler/gems/jsonapi-resources-30969a3b929d/lib/jsonapi/request.rb:24:in `initialize'
/var/www/api/shared/bundle/ruby/2.1.0/bundler/gems/jsonapi-resources-30969a3b929d/lib/jsonapi/acts_as_resource_controller.rb:88:in `new'
/var/www/api/shared/bundle/ruby/2.1.0/bundler/gems/jsonapi-resources-30969a3b929d/lib/jsonapi/acts_as_resource_controller.rb:88:in `setup_request'
```

because `params[:sort]` is equal to "" and `CSV.parse_line(URI.unescape("")` is nil

source:

``` ruby
  def parse_sort_criteria(sort_criteria)
      return unless sort_criteria

      @sort_criteria = CSV.parse_line(URI.unescape(sort_criteria)).collect do |sort|
        if sort.start_with?('-')
          sort_criteria = {field: unformat_key(sort[1..-1]).to_s}
          sort_criteria[:direction] = :desc
        else
          sort_criteria = {field: unformat_key(sort).to_s}
          sort_criteria[:direction] = :asc
        end

        check_sort_criteria(@resource_klass, sort_criteria)
        sort_criteria
      end
  end
```

**Comment by lgebhardt** [comment]
Good catch. Thanks
