### ISSUE TITLE
broken has_one for ActiveRecord has_one association

### ISSUE THREAD

**Issue by senid231** [JSONAPI-Resources/jsonapi-resources#300]
``` ruby
jsonapi_resources :authors do
    jsonapi_relationships
end
```

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail
end

class AuthorDetailResource < JSONAPI::Resource
end
```

``` ruby
class Author < ActiveRecord::Base
  has_one :author_detail
end

class AuthorDetail < ActiveRecord::Base
  belongs_to :author
end
```

when i trying to fetch resource it fails with:

```
Started GET "/authors/1" for 127.0.0.1 at 2015-07-09 00:38:46 +0300
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by AuthorsController#show as API_JSON
  Parameters: {"id"=>"1"}
  Author Load (0.4ms)  SELECT  "authors".* FROM "authors" WHERE "authors"."id" = $1  ORDER BY "authors"."id" ASC LIMIT 1  [["id", 1]]
Completed 500 Internal Server Error in 17ms

NameError (undefined method `author_detail_id' for class `Author'):
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource.rb:678:in `method'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource.rb:678:in `block (2 levels) in _associate'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:285:in `foreign_key_value'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:235:in `has_one_linkage'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:261:in `link_object_has_one'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:276:in `link_object'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:159:in `block in relationship_data'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:151:in `each'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:151:in `each_with_object'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:151:in `relationship_data'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:116:in `object_hash'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:95:in `process_primary'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/resource_serializer.rb:34:in `serialize_to_hash'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/response_document.rb:100:in `results_to_hash'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/response_document.rb:11:in `contents'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/acts_as_resource_controller.rb:138:in `render_results'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/acts_as_resource_controller.rb:159:in `process_request_operations'
  /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/jsonapi-resources-0331732aade9/lib/jsonapi/acts_as_resource_controller.rb:18:in `show'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/senid/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/senid/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/senid/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

cause this code

``` ruby
def _associate(klass, *attrs)
...
     if association.is_a?(JSONAPI::Association::HasOne)
     define_method foreign_key do
      @model.method(foreign_key).call
    end unless method_defined?(foreign_key)
...
end
```

defines correct method only for ActiveRecord belongs_to type of relation.
for ActiveRecord has_one it fails

i find a workaround:

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail

  def author_detail_id
    model.author_detail.try!(:id)
  end
end
```

but i think has_one in resources should have some option that allows to change it's behaviour

**Comment by senid231** [comment]
but this workaround will generate additional sql requests cause relationships for has_one relations always have id in data hash #299 
unless you do another workaround like

``` ruby
class AuthorResource < JSONAPI::Resource
  has_one :author_detail

  def author_detail_id
    model.author_detail.try!(:id)
  end

  def self.records_for(options = {})
    super.includes(:author_detail)
    # or
    # super.eager_load(:author_detail)
  end
end
```

**Comment by Fivell** [comment]
+1, 
@lgebhardt , what is the recommended solution  when working with active-record belongs_to ?

**Comment by lgebhardt** [comment]
I'll get this fixed soon. It broke in the latest release due to some work on the relations and eager loading.

Before both has_one and belongs_to could be treated as has_one when defining a resource. I think this may end up changing and we'll end up needing to distinguish between the two association types. I think has_one will end up using code very similar to the work around @senid231 shows (that's basically how has_many now works).
