### ISSUE TITLE
ActiveRecord coupling fix

### ISSUE THREAD

**Issue by oliverbarnes** [JSONAPI-Resources/jsonapi-resources#360]
Just updated to latest master, and came across this error complaining about missing AR

```
  1) Supports API GET /supports?filter[proposal_id]=:proposal_id&filter[participant_id]=:participant_id support resource
     Failure/Error: subject { get "/supports?#{filter_params}", {}, headers  }
     NameError:
       uninitialized constant ActiveRecord
     # /Users/work/.rvm/gems/ruby-2.2.2/bundler/gems/jsonapi-resources-72168924065f/lib/jsonapi/resource.rb:689:in `block in _add_relationship'
     # /Users/work/.rvm/gems/ruby-2.2.2/bundler/gems/jsonapi-resources-72168924065f/lib/jsonapi/resource.rb:685:in `each'
     # /Users/work/.rvm/gems/ruby-2.2.2/bundler/gems/jsonapi-resources-72168924065f/lib/jsonapi/resource.rb:685:in `_add_relationship'
     # /Users/work/.rvm/gems/ruby-2.2.2/bundler/gems/jsonapi-resources-72168924065f/lib/jsonapi/resource.rb:346:in `has_one'
     # ./app/resources/support_resource.rb:4:in `<class:SupportResource>'
     # ./app/resources/support_resource.rb:3:in `<top (required)>'
```

This app is using mongodb/mongoid, and so far I had been fixing the AR dependency like this:

``` ruby
# app/controllers/my_resource_controller.rb
class MyResourceController < ApplicationController
  include JSONAPI::ActsAsResourceController

  def create_operations_processor
    TempMongoidOperationsProcessor.new
  end
end

# lib/temp_mongoid_operations_processor.rb
class TempMongoidOperationsProcessor < JSONAPI::OperationsProcessor

  private

    def transaction
      # if @transactional
      #   ActiveRecord::Base.transaction do
      #     yield
      #   end
      # else
      yield
      # end
    end

    def rollback
      # raise ActiveRecord::Rollback if @transactional
    end

    def process_operation(operation)
      # operation.apply(@context)
      operation.apply
    # rescue ActiveRecord::DeleteRestrictionError => e
    #   record_locked_error = JSONAPI::Exceptions::RecordLocked.new(e.message)
    #   return JSONAPI::ErrorsOperationResult.new(record_locked_error.errors[0].code, record_locked_error.errors)

    rescue Mongoid::Errors::DocumentNotFound
      record_not_found = JSONAPI::Exceptions::RecordNotFound.new(operation.associated_key)
      return JSONAPI::ErrorsOperationResult.new(record_not_found.errors[0].code, record_not_found.errors)
    end
end
```

Is my fix outdated? Is there a new recommended fix to get non-AR ORM/ODMs going?

**Comment by lgebhardt** [comment]
@oliverbarnes Sorry about that. Can you please check if #362 fixes this?

**Comment by oliverbarnes** [comment]
@lgebhardt no worries, I've using #362's branch and it does fix it (I commented there a few days ago :) ). Thanks
