### ISSUE TITLE
ActionDispatch::Routing::Mapper::Scope no longer provides `[]=`

### ISSUE THREAD

**Issue by jashank** [JSONAPI-Resources/jsonapi-resources#380]
So, if I do, against Rails `master` (I'm at `32424b6bfb`) with JR (0.5.5+; I'm using `master` at `cc9ca2b6dc` here but only to see if it'd been fixed yet):

``` ruby
# $APP/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      jsonapi_resources :resource
    end
  end
end
```

I get a really big stacktrace vomited at me, apparently a side-effect of [`rails/rails#5e81e6ca31`](https://github.com/rails/rails/commit/5e81e6ca31aa0d2a38f8db5c8fe9bcbce98d9689) although I don't understand the intricacies around here so I have no idea what's going on or how to fix it:

```
$GEMS/jsonapi-resources-cc9ca2b6dcb1/lib/jsonapi/routing_ext.rb:80:in `block in jsonapi_resources': undefined method `[]=' for #<ActionDispatch::Routing::Mapper::Scope:0x0000080e78c7b8> (NoMethodError)
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1374:in `block (2 levels) in resources'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1710:in `block in resource_scope'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:821:in `controller'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1710:in `resource_scope'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1373:in `block in resources'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1702:in `with_scope_level'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1371:in `resources'
    from $GEMS/jsonapi-resources-cc9ca2b6dcb1/lib/jsonapi/routing_ext.rb:79:in `jsonapi_resources'
    from $APP/config/routes.rb:4:in `block (3 levels) in <top (required)>'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:875:in `block (2 levels) in namespace'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:806:in `scope'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:875:in `block in namespace'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1823:in `path_scope'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:874:in `namespace'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1482:in `namespace'
    from $APP/config/routes.rb:3:in `block (2 levels) in <top (required)>'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:875:in `block (2 levels) in namespace'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:806:in `scope'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:875:in `block in namespace'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1823:in `path_scope'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:874:in `namespace'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/mapper.rb:1482:in `namespace'
    from $APP/config/routes.rb:2:in `block in <top (required)>'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/route_set.rb:399:in `instance_exec'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/route_set.rb:399:in `eval_block'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/routing/route_set.rb:377:in `draw'
    from $APP/config/routes.rb:1:in `<top (required)>'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/dependencies.rb:296:in `load'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/dependencies.rb:296:in `block in load'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/dependencies.rb:296:in `load'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/routes_reloader.rb:40:in `each'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/routes_reloader.rb:16:in `reload!'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/routes_reloader.rb:26:in `block in updater'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/file_update_checker.rb:75:in `call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/file_update_checker.rb:75:in `execute'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/routes_reloader.rb:7:in `execute'
    from $GEMS/rails-32424b6bfbb8/railties/lib/rails/application/finisher.rb:81:in `block (2 levels) in <module:Finisher>'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:444:in `instance_exec'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:444:in `block in make_lambda'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:166:in `call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:166:in `block (2 levels) in halting'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:601:in `call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:600:in `catch'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:600:in `block in default_terminator'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:167:in `call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:167:in `block in halting'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:502:in `call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:502:in `block in call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:502:in `each'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:502:in `call'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:94:in `__run_callbacks__'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:814:in `_run_prepare_callbacks'
    from $GEMS/rails-32424b6bfbb8/activesupport/lib/active_support/callbacks.rb:83:in `run_callbacks'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
    from $GEMS/rails-32424b6bfbb8/actionpack/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
    from $GEMS/spring-1.3.6/lib/spring/application.rb:153:in `serve'
    from $GEMS/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
    from $GEMS/spring-1.3.6/lib/spring/application.rb:125:in `loop'
    from $GEMS/spring-1.3.6/lib/spring/application.rb:125:in `run'
    from $GEMS/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
    from ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

**Comment by jashank** [comment]
I have monkeypatched around this with

``` ruby
class ActionDispatch::Routing::Mapper::Scope
  def []=(k, v)
    @hash[k] = v
  end
end
```

but clearly this needs a better solution.

**Comment by barelyknown** [comment]
Let's see if that commit to Rails can be reverted. `[]=` was a public method, and it doesn't seem to me that it should have been removed. Can you take the lead on that @jashank?

**Comment by jashank** [comment]
I've filed rails/rails#21231, but I'm not hopeful; a major release gives them a valid excuse to remove bits.

I _think_ I now understand how this works, in any case, and may be able to write a patch for JR to get around this.

**Comment by jashank** [comment]
Oh, okay:

> That class is entirely private and should not be used directly. We removed a private API method but you can use public methods to archive (sic) the same.

I'll just finish testing this patch, and PR it.

**Comment by barelyknown** [comment]
Great. Thanks for filing the issue and chasing this down.

**Comment by jashank** [comment]
So I have a patch that looks like it should work.  Unfortunately, I can't test it because rails/rails is broken again; this time, it seems to be some refactoring that's broken (commit rails/rails@6ac882bb58b429d20b76c96975df7dabaf618988):

```
NoMethodError: undefined method `singleton?' for nil:NilClass
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/mapper.rb:1494:in `shallow?'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/mapper.rb:1463:in `block in nested'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/mapper.rb:1702:in `with_scope_level'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/mapper.rb:1462:in `nested'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/mapper.rb:1656:in `apply_common_behavior_for'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/mapper.rb:1367:in `resources'
jsonapi-resources@master/lib/jsonapi/routing_ext.rb:86:in `jsonapi_resources'
jsonapi-resources@master/test/test_helper.rb:101:in `block in <top (required)>'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/route_set.rb:399:in `instance_exec'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/route_set.rb:399:in `eval_block'
$GEMS/rails-9c0b40817650/actionpack/lib/action_dispatch/routing/route_set.rb:377:in `draw'
jsonapi-resources@master/test/test_helper.rb:99:in `<top (required)>'
jsonapi-resources@master/Rakefile:4:in `require'
jsonapi-resources@master/Rakefile:4:in `<top (required)>'
ruby-2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
ruby-2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
ruby-2.2.2/bin/rake:33:in `<main>'
```
