### ISSUE TITLE
500 internal error on nested route

### ISSUE THREAD

**Issue by lionelrudaz** [JSONAPI-Resources/jsonapi-resources#436]
Hi guys,

I've got an issue with my API. Under certain circonstances, I get a 500 internal error when I want to load nested resources.

In the example below, I'll show you the stack trace for a successful fetch for categories under a search and an error for doctors under a search.

I don't know what are the differences between them.
- A search has many categories
- A search has many doctors
- A doctor has many searches through distances
- A doctor has many distances
- A search has many distances

Here's the stack trace:

```
Started GET "/api/v1/searches/236/category" for ::1 at 2015-09-09 22:00:09 +0200
Processing by Api::V1::CategoriesController#get_related_resource as HTML
  Parameters: {"relationship"=>"category", "source"=>"api/v1/searches", "search_id"=>"236"}
  Search Load (0.4ms)  SELECT  "searches".* FROM "searches" WHERE "searches"."id" = $1  ORDER BY "searches"."id" ASC LIMIT 1  [["id", 236]]
  Category Load (0.3ms)  SELECT  "categories".* FROM "categories" WHERE "categories"."id" = $1 LIMIT 1  [["id", 1]]
  Category::Translation Load (0.4ms)  SELECT "category_translations".* FROM "category_translations" WHERE "category_translations"."category_id" = $1  [["category_id", 1]]
Completed 200 OK in 58ms (Views: 0.4ms | ActiveRecord: 8.2ms)


Started GET "/api/v1/searches/236/doctors" for ::1 at 2015-09-09 22:00:15 +0200
Processing by Api::V1::DoctorsController#get_related_resources as HTML
  Parameters: {"relationship"=>"doctors", "source"=>"api/v1/searches", "search_id"=>"236"}
  Search Load (0.6ms)  SELECT  "searches".* FROM "searches" WHERE "searches"."id" = $1  ORDER BY "searches"."id" ASC LIMIT 1  [["id", 236]]
Internal Server Error: undefined method `order' for nil:NilClass /Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/resource.rb:441:in `apply_sort'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/resource.rb:809:in `block (2 levels) in _add_relationship'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operation.rb:183:in `public_send'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operation.rb:183:in `apply'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:23:in `block in process_operation'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:90:in `with_default_handling'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:21:in `process_operation'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:53:in `block (5 levels) in process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_show_related_resources_operation_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:52:in `block (4 levels) in process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_operation_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:50:in `block (3 levels) in process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:45:in `each'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:45:in `block (2 levels) in process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:10:in `transaction'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:41:in `block in process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_operations_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:40:in `process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:167:in `process_request_operations'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:54:in `get_related_resources'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:308:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:308:in `block (2 levels) in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/route_translator-4.0.0/lib/route_translator/extensions/action_controller.rb:20:in `set_locale_from_url'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:307:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:307:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/meta_request-0.3.4/lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/meta_request-0.3.4/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:378:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:84:in `protected_app_call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:79:in `better_errors_call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-contrib-1.4.0/lib/rack/contrib/response_headers.rb:17:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/meta_request-0.3.4/lib/meta_request/middlewares/headers.rb:16:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/middleware.rb:39:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/Users/lionelrudaz/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/lionelrudaz/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/lionelrudaz/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/lionelrudaz/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
Completed 500 Internal Server Error in 22ms (Views: 0.5ms | ActiveRecord: 2.1ms)
```

You can find my repo here: https://github.com/lionelrudaz/wellnow-api/tree/jsonapi

It seems to be an issue with sorting, but I don't understand what can be wrong.

Let me know if you need more information. Thanks in advance.

Cheers,

Lionel

**Comment by lgebhardt** [comment]
In your Search model you have a method called `doctors`. This is overriding the relationship that the SearchResource is counting on returning the Doctors relation.

**Comment by lionelrudaz** [comment]
I was sure it was a newbie thing. Thanks a lot for your help.
