### ISSUE TITLE
Include resources getting uninitialized constant ActiveRecordOperationsProcessor::ActiveRecord

### ISSUE THREAD

**Issue by flybayer** [JSONAPI-Resources/jsonapi-resources#441]
I'm using 
- `jsonapi-resources` 0.5.9
- neo4j database with the neo4j gem (5.2.3) which doesn't use ActiveRecord.
- namespaced resources (`API::OrgResource`)

**Everything is working great so far except for including resources like this:**

```
http://app.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb?include=roles
```

``` json
{
    "errors": 
    [
        {
            "title": "Internal Server Error",
            "detail": "Internal Server Error",
            "id": null,
            "href": null,
            "code": 500,
            "source": null,
            "links": null,
            "status": "500"
        }
    ]
}
```

**Without the include parameter works fine, and I get this:**

```
http://app.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb
```

``` json
{
    "data": 
    { 
        "id": "604b66a5-c29f-46b9-a420-35098b1bdcbb",
        "type": "orgs",
        "links": 
         {
            "self": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb"
         },
         "attributes": 
          {
             "created-at": "2015-08-26T00:49:21.000+00:00",
             "updated-at": "2015-08-26T00:49:21.000+00:00",
             "name": "Kemmer, Oberbrunner and Hoeger"
         },
         "relationships": 
         {
            "people": 
            {
                "links": 
                {
                     "self": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/relationships/people",
                     "related": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/people"
                 }
             },
             "roles": 
             {
                 "links": 
                 {
                     "self": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/relationships/roles",
                     "related": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/roles"
                 }
             }
        }
    }
}
```

**Here's the error as reported from log/development.log when trying to include a resource:**

``` ruby
Started GET "/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb?include=roles" for 127.0.0.1 at 2015-09-10 17:16:10 -0500
Processing by API::OrgsController#show as HTML
  Parameters: {"include"=>"roles", "id"=>"604b66a5-c29f-46b9-a420-35098b1bdcbb"}
Internal Server Error: uninitialized constant ActiveRecordOperationsProcessor::ActiveRecord /Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:24:in `rescue in block in process_operation'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:22:in `block in process_operation'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:90:in `with_default_handling'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:21:in `process_operation'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:53:in `block (5 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_show_operation_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:52:in `block (4 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_operation_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:50:in `block (3 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:45:in `each'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:45:in `block (2 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/active_record_operations_processor.rb:10:in `transaction'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:41:in `block in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_operations_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:40:in `process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:167:in `process_request_operations'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:18:in `show'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
```

**However, when I serialize it from the rails console like this, it works great and includes the roles!**

``` ruby
JSONAPI::ResourceSerializer.new(API::OrgResource, include: ['roles']).serialize_to_hash(API::OrgResource.new(Org.first))
```

**My Models**

``` ruby
class Org
  include Neo4j::ActiveNode
  include Neo4j::Timestamps
  property :name, type: String

  has_many :in, :people, origin: :org
  has_many :in, :roles, origin: :org

  validates :name, presence: true
end

class Role
  include Neo4j::ActiveNode
  include Neo4j::Timestamps
  property :name, type: String

  has_one :out, :org, type: :IN_ORG
  has_many :out, :people, rel_class: :FilledBy

  validates :name, presence: true
end

```

**My Resources**

``` ruby
class API::BaseResource < JSONAPI::Resource
  abstract
  attributes :created_at, :updated_at
end

class API::OrgResource < API::BaseResource
  attributes :name
  has_many :people
  has_many :roles
end

class API::RoleResource < API::BaseResource
  attributes :name
  has_one :org
  has_many :people
end

```

**My Controllers**

``` ruby
class API::OrgsController < ApplicationController
end

class API::RolesController < ApplicationController
end
```

Any ideas??

**Comment by lgebhardt** [comment]
Try switching the OperationsProcessor to the Basic one in the Configuration.

``` ruby
self.operations_processor = :basic
```

**Comment by flybayer** [comment]
@lgebhardt, well, it still doesn't work, but it has a different error this time...

It's getting hung up here: https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L421

``` ruby
Started GET "/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb?include=roles" for 127.0.0.1 at 2015-09-15 19:19:50 -0500
Processing by API::OrgsController#show as HTML
  Parameters: {"include"=>"roles", "id"=>"604b66a5-c29f-46b9-a420-35098b1bdcbb"}
Internal Server Error: undefined method `includes' for Org(created_at: DateTime, name: String, updated_at: DateTime):Class /Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/resource.rb:428:in `apply_includes'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/resource.rb:512:in `find_by_key'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operation.rb:82:in `apply'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:85:in `block in process_operation'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:90:in `with_default_handling'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:84:in `process_operation'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:53:in `block (5 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_show_operation_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:52:in `block (4 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_operation_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:50:in `block (3 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:45:in `each'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:45:in `block (2 levels) in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:74:in `transaction'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:41:in `block in process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_operations_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/operations_processor.rb:40:in `process'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:167:in `process_request_operations'
/Users/BBayer0/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:18:in `show'
```

**Comment by feedthebayer** [comment]
I think there may be something else going on here... The basic response without side-loading doesn't include a `data` structure for the resource, only a `links` one.

```
http://app.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb
```
```json
{
    "data": 
    { 
        "id": "604b66a5-c29f-46b9-a420-35098b1bdcbb",
        "type": "orgs",
        "links": 
         {
            "self": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb"
         },
         "attributes": 
          {
             "created-at": "2015-08-26T00:49:21.000+00:00",
             "updated-at": "2015-08-26T00:49:21.000+00:00",
             "name": "Kemmer, Oberbrunner and Hoeger"
         },
         "relationships": 
         {
            "people": 
            {
                "links": 
                {
                     "self": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/relationships/people",
                     "related": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/people"
                 }
             },
             "roles": 
             {
                 "links": 
                 {
                     "self": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/relationships/roles",
                     "related": "http://genus-api.dev/api/orgs/604b66a5-c29f-46b9-a420-35098b1bdcbb/roles"
                 }
             }
        }
    }
}
```
