### ISSUE TITLE
"undefined method `class_methods' for JSONAPI::ActsAsResourceController:Module" in 0.5.9

### ISSUE THREAD

**Issue by jeffreybiles** [JSONAPI-Resources/jsonapi-resources#476]
Hey!

I'm getting an error anytime I run rails with jsonapi-resource 0.5.9.  I am able to run normally with 0.5.8.

This is the stack trace:

```
/Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:196:in `<module:ActsAsResourceController>': undefined method `class_methods' for JSONAPI::ActsAsResourceController:Module (NoMethodError)
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:4:in `<module:JSONAPI>'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/jsonapi-resources-0.5.9/lib/jsonapi/acts_as_resource_controller.rb:3:in `<top (required)>'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/jsonapi-resources-0.5.9/lib/jsonapi-resources.rb:3:in `require'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/jsonapi-resources-0.5.9/lib/jsonapi-resources.rb:3:in `<top (required)>'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `require'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `each'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `each'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `require'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/bundler-1.6.1/lib/bundler.rb:132:in `require'
    from /Users/jeffreybiles/screencasts/monster-demo/rails-api/config/application.rb:7:in `<top (required)>'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `require'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `block in server'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/jeffreybiles/screencasts/monster-demo/rails-api/bin/rails:8:in `require'
    from /Users/jeffreybiles/screencasts/monster-demo/rails-api/bin/rails:8:in `<top (required)>'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `load'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `call'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/lib/spring/client.rb:28:in `run'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/bin/spring:49:in `<top (required)>'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `load'
    from /Users/jeffreybiles/.rvm/gems/ruby-2.1.1/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `<top (required)>'
    from /Users/jeffreybiles/screencasts/monster-demo/rails-api/bin/spring:13:in `require'
    from /Users/jeffreybiles/screencasts/monster-demo/rails-api/bin/spring:13:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

The project is relatively new, and 0.5.9 was giving me trouble even before creating my first resource.  Is there a configuration I need to set or something?

My Rails version is 4.1.7 and my Ruby version is 2.1.1

**Comment by lgebhardt** [comment]
How are you setting up your controller - including `JSONAPI::ActsAsResourceController` or deriving from `JSONAPI::ResourceController`?

**Comment by jeffreybiles** [comment]
I have been using `JSONAPI::ResourceController`. 

 However, I did a quick check with `JSONAPI::ActsAsResourceController` and it has an error message exactly the same (AFAICT) as the one above.

**Comment by davidstosik** [comment]
You probably found out by now, but `class_methods` was introduced in [Rails 4.2](http://apidock.com/rails/ActiveSupport/Concern/class_methods).
JSONAPI::Resources started using it in 0.5.9, and my pull request: #426 to revert it is part of the v0.6.0 release, so you shouldn't have issues with more recent versions.

**Comment by jeffreybiles** [comment]
Awesome, thanks!
