### ISSUE TITLE
Filter using Array as value fails

### ISSUE THREAD

**Issue by ryanbillingsley** [JSONAPI-Resources/jsonapi-resources#497]
Using 0.6.0

Trying to use a filter like so:

`?filter[users][]=1&filter[users][]=2`

which Rails parses to `{"filter"=>{"users"=>["1","2"]}}`

This results in a crash, because the CSV parsing that happens in `verify_filter` is causing an exception to be thrown:

```
Internal Server Error: private method `gets' called for ["1"]:Array /usr/local/var/rbenv/versions/2.2.1/lib/ruby/2.2.0/csv.rb:1798:in `block in shift'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/2.2.0/csv.rb:1796:in `loop'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/2.2.0/csv.rb:1796:in `shift'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/2.2.0/csv.rb:1315:in `parse_line'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.5/lib/jsonapi/resource.rb:538:in `verify_filter'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.5/lib/jsonapi/resource.rb:526:in `block in verify_filters'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.5/lib/jsonapi/resource.rb:525:in `each'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.5/lib/jsonapi/resource.rb:525:in `verify_filters'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.5.5/lib/jsonapi/operation.rb:45:in `apply'
```

**Comment by lgebhardt** [comment]
We definitely need to protect against the crash.

The code expects it in the format of `?filter[users]='1,2'`. Is it possible for you to change the format?

**Comment by ryanbillingsley** [comment]
@lgebhardt I can change the format.  The way I discovered this was using Ember Data's JSON API Adapter.  If you use `this.store.find('carts',{'filter[users]': [1,2,3]});` it will serialize the query param into the example format I posted.  I just joined the array into a string, but worth noting that the two treat this differently.  I know the spec for JSON API doesn't give any indication of how filtering should work, so not sure if anything can be done about it.

**Comment by lgebhardt** [comment]
@ryanbillingsley I believe the spec used to have an opinion on formatting and we're following that old format. If Ember Data is using this other one we should probably try to support it as well. Without the spec taking a stand on things like this we will run into incompatibilities. As you say I'm not sure what can be done about it.

**Comment by kyungbae** [comment]
Using 0.7.0, I found the same bug. 

Using `verify` option with a filter will not work since CSV parsing is triggered right before checking the options with the filter. Overriding `verify_filter` will work even if it has been deprecated in 0.7.0.

**Comment by nixpulvis** [comment]
Kinda off topic but possibly related. Is a request like `/models?filter[date]=today&filter[date]=1pm` supposed to give me an array of two values? I know that in Rails you generally add the `[]` to signify an array, and otherwise the API gives back a single value. Here  it seems we always get back an array.
