### ISSUE TITLE
Gem Load Error is: private method `include' called for JSONAPI::ResourceController:Class

### ISSUE THREAD

**Issue by sjauld** [JSONAPI-Resources/jsonapi-resources#774]
Currently using 0.7.1.beta2
ruby 2.0.0-p645

```
Gem Load Error is: private method `include' called for JSONAPI::ResourceController:Class
Backtrace for gem load error is:
.../gems/jsonapi-resources-0.7.1.beta2/lib/jsonapi/acts_as_resource_controller.rb:10:in `included'
.../gems/jsonapi-resources-0.7.1.beta2/lib/jsonapi/resource_controller.rb:3:in `include'
.../gems/jsonapi-resources-0.7.1.beta2/lib/jsonapi/resource_controller.rb:3:in `<class:ResourceController>'
.../gems/jsonapi-resources-0.7.1.beta2/lib/jsonapi/resource_controller.rb:2:in `<module:JSONAPI>'
.../gems/jsonapi-resources-0.7.1.beta2/lib/jsonapi/resource_controller.rb:1:in `<top (required)>'
.../gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
.../gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
.../gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
.../gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
.../gems/jsonapi-resources-0.7.1.beta2/lib/jsonapi-resources.rb:5:in `<top (required)>'
.../gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
.../gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
.../gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
.../gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
.../gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
.../gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
.../gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
```

Problem triggering it is:
https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L10

**Comment by lgebhardt** [comment]
Back in February support for Ruby 2.0 was dropped. https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

About that JR also dropped support for Ruby 2.0 in order to enable use of some Ruby 2.1 features. I suspect this is related, though I haven't tested it.
