### ISSUE TITLE
Relationships on subclasses don't adhere to model name

### ISSUE THREAD

**Issue by jraunio** [JSONAPI-Resources/jsonapi-resources#823]
A LoadError is thrown when trying to load a resource model with a namespaced custom model name that inherits from a abstract resource model that declares a relation.

Verified in versions `0.8.0.beta2` and `0.7.0`

Modules:

``` ruby
module API
  module V2
    module Packages
      class PackageResource < BaseResource
        abstract
        has_many :venues
      end
    end
  end
end
```

``` ruby
module API
  module V2
    module Packages
      class MeetingPackageResource < PackageResource
        model_name 'Packages::MeetingPackage'
        has_many :services, class_name: 'MeetingPackageService'
      end
    end
  end
end
```

Path to meeting package module:

```
app/models/packages/meeting_package.rb
```

Error stack trace:

```
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant MeetingPackage, expected /app/models/packages/meeting_package.rb to define it (LoadError)
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:77:in `safe_constantiz
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:934:in `_model_class'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:974:in `block in _add_relationship'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:970:in `each'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:970:in `_add_relationship'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:411:in `block in inherited'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:408:in `each_value'
/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:408:in `inherited'
/app/resources/api/v2/packages/meeting_package_resource.rb:4:in `<module:Packages>'
/app/resources/api/v2/packages/meeting_package_resource.rb:3:in `<module:V2>'
/app/resources/api/v2/packages/meeting_package_resource.rb:2:in `<module:API>'
/app/resources/api/v2/packages/meeting_package_resource.rb:1:in `<top (required)>'
...

```

**Comment by valscion** [comment]
I created a sample rails application for this issue that can be ran with `bin/rails server` and see the error raised:

https://github.com/valscion/jr-823-repro

Judging by how JR works, it might be because by the time we start defining relationships on the subclasses, the `model_name` has not yet been called and the automatic constant loading fails. Even though we're using `safe_constantize`, we get an error because Rails actually finds the file for the constant but then throws up when that file does not define the constant we wanted.

https://github.com/cerebris/jsonapi-resources/blob/v0.8.0.beta2/lib/jsonapi/resource.rb#L405-L413

``` rb
module JSONAPI
  class Resource
    class << self
      def inherited(subclass)
        subclass.abstract(false)
        subclass.immutable(false)
        subclass._attributes = (_attributes || {}).dup
        subclass._model_hints = (_model_hints || {}).dup

        subclass._relationships = {}
        # Add the relationships from the base class to the subclass using the original options
        if _relationships.is_a?(Hash)
          _relationships.each_value do |relationship|
            options = relationship.options.dup
            options[:parent_resource] = subclass
            subclass._add_relationship(relationship.class, relationship.name, options)
          end
        end

        # -- snip --
      end
    end
  end
end
```

It might be that this use case cannot be supported — that is, an abstract resource defining a relationship for a subclass whose underlying model cannot be figured out by using `class_name.demodulize` that [is the default for `Resource#_model_name` method](https://github.com/cerebris/jsonapi-resources/blob/v0.8.0.beta2/lib/jsonapi/resource.rb#L883):

``` rb
def _model_name
  _abstract ? '' : @_model_name ||= name.demodulize.sub(/Resource$/, '')
end
```

**Comment by valscion** [comment]
Oh sorry, that reproduction isn't actually exactly what's happening... I had a bug there. I fixed that, so the reproduction can still be ran with an exception.

So I figured out why the crash comes out. It is due to a weird eager_load config we have, so that's not actually the fault of JR.

Without the config, this is what is output:

```
$ bin/rails server
=> Booting WEBrick
=> Rails 4.2.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[MODEL NOT FOUND] Model could not be found for Api::MyNamespace::AuthorResource. If this a base Resource declare it as abstract.
[2016-09-07 14:55:22] INFO  WEBrick 1.3.1
[2016-09-07 14:55:22] INFO  ruby 2.1.2 (2014-05-08) [x86_64-darwin14.0]
[2016-09-07 14:55:22] INFO  WEBrick::HTTPServer#start: pid=5526 port=3000
```

but when I add the bad config:

``` rb
config.eager_load_paths += Dir["#{config.root}/app/models/**/"]
```

...I get this error that is the same as in this bug report:

<details>
<summary>

Output of `bin/rails server`</summary>



```
=> Booting WEBrick
=> Rails 4.2.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant Author, expected /Users/vesa/code/muut/jr-823-repro/app/models/my_namespace/author.rb to define it (LoadError)
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:77:in `safe_constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:934:in `_model_class'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:974:in `block in _add_relationship'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:970:in `each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:970:in `_add_relationship'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:411:in `block in inherited'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:408:in `each_value'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:408:in `inherited'
        from /Users/vesa/code/muut/jr-823-repro/app/resources/api/my_namespace/author_resource.rb:3:in `<module:MyNamespace>'
        from /Users/vesa/code/muut/jr-823-repro/app/resources/api/my_namespace/author_resource.rb:2:in `<module:Api>'
        from /Users/vesa/code/muut/jr-823-repro/app/resources/api/my_namespace/author_resource.rb:1:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:457:in `load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:457:in `block in load_file'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:456:in `load_file'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:354:in `require_or_load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `const_get'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `block in constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:77:in `safe_constantize'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/resource.rb:429:in `resource_for'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonapi-resources-0.8.0.beta2/lib/jsonapi/routing_ext.rb:75:in `jsonapi_resources'
        from /Users/vesa/code/muut/jr-823-repro/config/routes.rb:59:in `block (3 levels) in <top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:882:in `block in namespace'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:817:in `scope'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:882:in `namespace'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1456:in `namespace'
        from /Users/vesa/code/muut/jr-823-repro/config/routes.rb:58:in `block (2 levels) in <top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:882:in `block in namespace'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:817:in `scope'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:882:in `namespace'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1456:in `namespace'
        from /Users/vesa/code/muut/jr-823-repro/config/routes.rb:57:in `block in <top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
        from /Users/vesa/code/muut/jr-823-repro/config/routes.rb:1:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:40:in `each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:75:in `call'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:75:in `execute'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:27:in `updater'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
        from /Users/vesa/code/muut/jr-823-repro/config/environment.rb:5:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from /Users/vesa/code/muut/jr-823-repro/config.ru:3:in `block in <main>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /Users/vesa/code/muut/jr-823-repro/config.ru:in `new'
        from /Users/vesa/code/muut/jr-823-repro/config.ru:in `<main>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:78:in `start'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/vesa/code/muut/jr-823-repro/bin/rails:9:in `require'
        from /Users/vesa/code/muut/jr-823-repro/bin/rails:9:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vesa/code/muut/jr-823-repro/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

</details>  

So it seems that the actual bug is in JR not finding the correct model for the subclass. The fact that we had this invalid config in place caused Rails to go haywire, otherwise JR would've just warned for this case.

**Comment by valscion** [comment]
This is the diff that causes the error to be shown, and the exception to be raised thanks to the unfortunate configuration change:

[Link to comparison](https://github.com/valscion/jr-823-repro/compare/20a768...9b7468c)

``` diff
diff --git a/app/resources/api/my_namespace/author_resource.rb b/app/resources/api/my_namespace/author_resource.rb
new file mode 100644
index 0000000..ae14b3d
--- /dev/null
+++ b/app/resources/api/my_namespace/author_resource.rb
@@ -0,0 +1,7 @@
+module Api
+  module MyNamespace
+    class AuthorResource < BaseResource
+      model_name 'MyNamespace::Author'
+    end
+  end
+end
diff --git a/app/resources/api/my_namespace/base_resource.rb b/app/resources/api/my_namespace/base_resource.rb
new file mode 100644
index 0000000..5da1ce3
--- /dev/null
+++ b/app/resources/api/my_namespace/base_resource.rb
@@ -0,0 +1,8 @@
+module Api
+  module MyNamespace
+    class BaseResource < JSONAPI::Resource
+      abstract
+      has_many :posts
+    end
+  end
+end
diff --git a/app/resources/api/my_namespace/post_resource.rb b/app/resources/api/my_namespace/post_resource.rb
new file mode 100644
index 0000000..624aba2
--- /dev/null
+++ b/app/resources/api/my_namespace/post_resource.rb
@@ -0,0 +1,6 @@
+module Api
+  module MyNamespace
+    class PostResource < JSONAPI::Resource
+    end
+  end
+end
diff --git a/config/application.rb b/config/application.rb
index f04486d..185fbcd 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -22,5 +22,8 @@ class Application < Rails::Application

     # Do not swallow errors in after_commit/after_rollback callbacks.
     config.active_record.raise_in_transactional_callbacks = true
+
+    # Load models from subfolders
+    config.eager_load_paths += Dir["#{config.root}/app/models/**/"]
   end
 end
diff --git a/config/routes.rb b/config/routes.rb
index 3f66539..4c78967 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -53,4 +53,10 @@
   #     # (app/controllers/admin/products_controller.rb)
   #     resources :products
   #   end
+
+  namespace :api do
+    namespace :my_namespace do
+      jsonapi_resources :author
+    end
+  end
 end
```

**Comment by valscion** [comment]
We eventually ended up using `ActiveSupport::Concern` and composition to allow for this shared functionality to work. If anyone is interested in a code example of how it looks like, we'll be happy to provide it :smile:. Basically it boils down to this:

``` rb
module MySharedFunctionality
  include ActiveSupport::Concern

  included do
    has_many :posts
  end
end

class AuthorResource
  model_name 'MyNamespace::Author'
  include MySharedFunctionality
end
```

This allow the `model_name` to be applied prior to the `included` block being ran from the `MySharedFunctionality`.

This approach might even be a more powerful way of creating reusable, shared modules which the current `abstract` base class pattern tries to provide..?

**Comment by btz1211** [comment]
@valscion, I am doing something similar. so I have
```
  class TestResource <  JSONAPI::Resource
     ...    
```

and

```
  class InheritTestResource <  TestResource
     ...    
```

I want the links `self` and `relationships` to be `api/tests/123` instead of `api/inherited-tests/123`. Is this possible?

**Comment by valscion** [comment]
This use case seems to be something else than this issue, so please let's not pollute this issue with questions not focusing on the issue
