### ISSUE TITLE
500 Internal Server Error - Invalid JSON data

### ISSUE THREAD

**Issue by koraykoska** [JSONAPI-Resources/jsonapi-resources#881]
When I send an `PATCH` request with invalid JSON data to the server, I get the following as a response:

`500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

and in the log file the following:

```
App 32245 stderr: Error during failsafe response: 784: unexpected token at '{
App 32245 stderr:   "data": {
App 32245 stderr:     "id": 2
App 32245 stderr:     "type": "users",
App 32245 stderr:     "attributes": {
App 32245 stderr:       "first-name": "M.C.",
App 32245 stderr:       "last-name": "McMaster"
App 32245 stderr:     }
App 32245 stderr:   }
App 32245 stderr: }'
```

I know, there is a comma missing but it probably should not return `500 Internal Server Error`.

I haven't tried other requests than `PATCH` yet but I wanted to open an issue before I forget it.

I am using the latest stable jsonapi-resources (v0.8.1) together with Rails 5.0.0 and Ruby 2.3.1.

**Comment by Petesta** [comment]
I believe returning a `500 Internal Server Error` follows the standard as stated at [jsonapi](http://jsonapi.org/format/#errors). What response are you expecting it to be?

Since it is malformed data that is just trying to be processed by the server it is allowed to return a `500` response error.

Unless you whitelist the specific exception that is occurring you won't be able to handle it yourself. In [README.md](https://github.com/cerebris/jsonapi-resources#raising-errors).

**Comment by Ybrin** [comment]
I am sorry, I think I missed this part of the documentation. Thank you for clearing things up @Petesta

**Comment by koraykoska** [comment]
The problem is, we don't get a rendered json error response but instead the default rails 500.html. This is the bug I am talking about @Petesta

**Comment by Petesta** [comment]
@Ybrin Ahh, that's a little more specific now. Mentioning the Rails `500.html` page. I thought you were just receiving a `500 Internal Server Error` JSON response.

But you're right, I got the same response. Here's mine.

```
JSON::ParserError at /endpoint
==============================

> 743: unexpected token at '{"data":{"type",:"foo"}'

json (2.0.2) lib/json/common.rb, line 156
-----------------------------------------

  151     #   additions even if a matching class and create_id was found. This option
  152     #   defaults to false.
  153     # * *object_class*: Defaults to Hash
  154     # * *array_class*: Defaults to Array
  155     def parse(source, opts = {})
> 156       Parser.new(source, opts).parse
  157     end
  158
  159     # Parse the JSON document _source_ into a Ruby data structure and return it.
  160     # The bang version of the parse method defaults to the more dangerous values
  161     # for the _opts_ hash, so be sure only to parse trusted _source_ documents.

App backtrace
-------------



Full backtrace
--------------

 - json (2.0.2) lib/json/common.rb:156:in `parse'
 - jsonapi-resources (0.8.0.beta2) lib/jsonapi/mime_types.rb:22:in `block in parser'
 - actionpack (5.0.0) lib/action_dispatch/http/parameters.rb:66:in `parse_formatted_parameters'
 - actionpack (5.0.0) lib/action_dispatch/http/request.rb:366:in `block in POST'
 - rack (2.0.1) lib/rack/request.rb:57:in `fetch_header'
 - actionpack (5.0.0) lib/action_dispatch/http/request.rb:365:in `POST'
 - actionpack (5.0.0) lib/action_dispatch/http/parameters.rb:35:in `parameters'
 - actionpack (5.0.0) lib/action_dispatch/http/filter_parameters.rb:41:in `filtered_parameters'
 - actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:21:in `process_action'
 - actionpack (5.0.0) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
 - activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 - actionpack (5.0.0) lib/abstract_controller/base.rb:126:in `process'
 - actionpack (5.0.0) lib/action_controller/metal.rb:190:in `dispatch'
 - actionpack (5.0.0) lib/action_controller/metal.rb:262:in `dispatch'
 - actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 - actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
 - actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
 - actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
 - actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
 - bullet (5.2.0) lib/bullet/rack.rb:10:in `call'
 - rack (2.0.1) lib/rack/etag.rb:25:in `call'
 - rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
 - rack (2.0.1) lib/rack/head.rb:12:in `call'
 - activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
 - activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
 - activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
 - activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
 - actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
 - railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
 - railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
 - activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
 - activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
 - railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
 - rack (2.0.1) lib/rack/runtime.rb:22:in `call'
 - activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
 - actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
 - rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
 - rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
 - sentry-raven (2.0.2) lib/raven/integrations/rack.rb:50:in `call'
 - rack-mini-profiler (0.10.1) lib/mini_profiler/profiler.rb:278:in `call'
 - railties (5.0.0) lib/rails/engine.rb:522:in `call'
 - puma (3.6.0) lib/puma/configuration.rb:225:in `call'
 - puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
 - puma (3.6.0) lib/puma/server.rb:415:in `process_client'
 - puma (3.6.0) lib/puma/server.rb:275:in `block in run'
 - puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

I've submitted a PR for this but not sure if there's a better way to handle it.

**Comment by Petesta** [comment]
https://github.com/cerebris/jsonapi-resources/pull/895

**Comment by lgebhardt** [comment]
I can see how that would happen. I'll try to get a fix soon.

Edit: Sorry, missed that a PR was provided. I'll review soon.

**Comment by Petesta** [comment]
@lgebhardt Ahh, no worries. Yea, I created a PR to help resolve this issue.
